import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const readStyleModules = (names: string[]) =>
  names.map((name) => readFileSync(join("src/styles", name), "utf8")).join("\n");

describe("style module boundaries", () => {
  it("keeps the CSS entrypoint as an ordered module manifest", () => {
    const entry = readFileSync("src/styles.css", "utf8").trim().split("\n");

    expect(entry).toEqual([
      '@import "photoswipe/style.css";',
      '@import "./styles/theme.css";',
      '@import "./styles/foundation.css";',
      '@import "./styles/blog.css";',
      '@import "./styles/attachments.css";',
      '@import "./styles/travel.css";',
      '@import "./styles/records-memory.css";',
      '@import "./styles/agenda-list.css";',
      '@import "./styles/agenda-cockpit.css";',
      '@import "./styles/agenda-cockpit-responsive.css";',
      '@import "./styles/agenda-program.css";',
      '@import "./styles/agenda-program-responsive.css";',
      '@import "./styles/rendered-org.css";',
      '@import "./styles/blog-rendered.css";',
      '@import "./styles/responsive.css";',
    ]);
  });

  it("keeps product CSS modules below the monolith threshold", () => {
    const modules = readdirSync("src/styles").filter((name) => name.endsWith(".css"));
    const lineCounts = modules.map((name) => ({
      name,
      lines: readFileSync(join("src/styles", name), "utf8").split("\n").length - 1,
    }));

    expect(lineCounts).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ name: "travel.css" }),
        expect.objectContaining({ name: "theme.css" }),
        expect.objectContaining({ name: "agenda-program.css" }),
        expect.objectContaining({ name: "rendered-org.css" }),
      ]),
    );
    expect(Math.max(...lineCounts.map(({ lines }) => lines))).toBeLessThanOrEqual(1200);
  });

  it("roots the visual system in package-backed theme tokens", () => {
    const theme = readFileSync("src/styles/theme.css", "utf8");

    expect(theme).toContain(
      "Generated by scripts/build-elegant-theme.mjs from tokens/elegant.json.",
    );
    expect(theme).toContain('@import "@radix-ui/colors/slate.css";');
    expect(theme).toContain('@import "@radix-ui/colors/blue.css";');
    expect(theme).toContain("@fontsource-variable/inter/files/inter-latin-wght-normal.woff2");
    expect(theme).toContain("@fontsource/roboto-mono/files/roboto-mono-latin-400-normal.woff2");
    expect(theme).toContain("@fontsource/roboto-mono/files/roboto-mono-latin-500-normal.woff2");
    expect(theme).toContain("--face-strong:");
    expect(theme).toContain("--face-salient:");
    expect(theme).toContain("--face-faded:");
    expect(theme).toContain("--surface-subtle:");
    expect(theme).toContain("--shadow-reading: 0 1px 0 var(--slate-a3);");
    expect(theme).toContain("--radius-label: 5px;");
    expect(theme).toContain("--frame-inset:");
    expect(theme).toContain("--reader-gutter:");
    expect(theme).toContain("--reader-width: 72ch;");
    expect(theme).toContain("--divider-width: 2px;");
    expect(theme).toContain("--weight-heavy: 700;");
    expect(theme).toContain("--type-body-trim-before:");
  });

  it("keeps generated theme variables aligned with the token contract", () => {
    const theme = readFileSync("src/styles/theme.css", "utf8");
    const tokens = JSON.parse(readFileSync("tokens/elegant.json", "utf8")) as Record<
      string,
      { value: string }
    >;

    for (const tokenName of Object.keys(tokens)) {
      expect(theme, tokenName).toContain(`--${tokenName}:`);
    }

    const packageJson = JSON.parse(readFileSync("package.json", "utf8")) as {
      scripts: Record<string, string>;
    };
    expect(packageJson.scripts["generate:theme"]).toBe("node scripts/build-elegant-theme.mjs");
    expect(packageJson.scripts.build).toContain("npm run generate:theme");
  });

  it("keeps typography and product surfaces on semantic tokens", () => {
    const styles = readdirSync("src/styles")
      .filter((name) => name.endsWith(".css"))
      .map((name) => readFileSync(join("src/styles", name), "utf8"))
      .join("\n");
    const travel = readFileSync("src/styles/travel.css", "utf8");

    expect(styles).not.toMatch(/font-size:\s*clamp\(/);
    expect(styles).toContain("padding: 14px var(--frame-inset);");
    expect(styles).toContain("gap: var(--reader-gutter);");
    expect(styles).toContain("border-left: var(--divider-width) solid var(--hairline);");
    expect(styles).toContain(".blog-index");
    expect(styles).toContain(".blog-time-thresholds");
    expect(styles).toContain(".blog-tag-filter");
    expect(styles).toContain(".blog-reasoning-paths");
    expect(styles).toContain(".blog-index-article");
    expect(styles).toContain('#app[data-reader-mode="zen"] .site-header');
    expect(styles).toContain(".blog-reader.is-zen .blog-article > h1:first-child");
    expect(styles).toContain("text-align: center;");
    expect(styles).not.toContain(".blog-time-point");
    expect(styles).not.toContain(".zen-toolbar");
    expect(styles).not.toContain(".blog-rail");
    expect(styles).not.toContain("article-switcher");
    expect(styles).toContain(".source-select");
    expect(styles).toContain(".source-select-root");
    expect(styles).toContain('.source-select-item[data-selected="true"]');
    expect(styles).not.toContain(".source-select option");
    expect(styles).not.toContain("nav button.active");
    expect(styles).toContain(
      ".site-nav-item.active {\n  border-left-color: var(--face-salient);\n  background: transparent;\n}",
    );
    expect(styles).toContain(".source-feed {\n  display: none;");
    expect(styles).toContain(".source-block--summary");
    expect(styles).toContain(".org-record-workbench .card-grid");
    expect(styles).toContain("grid-template-columns: minmax(0, var(--reader-wide-width));");
    expect(travel).toContain("color: var(--face-strong);");
    expect(travel).toContain("background: var(--surface-paper);");
    expect(travel).toContain("border: 1px solid var(--hairline");
    expect(travel).not.toContain('data-layout="single"');
  });

  it("keeps core reading surfaces within the elegant face economy", () => {
    const coreStyles = readStyleModules([
      "foundation.css",
      "blog.css",
      "attachments.css",
      "travel.css",
      "records-memory.css",
      "rendered-org.css",
    ]);

    expect(coreStyles).not.toMatch(/#[0-9a-fA-F]{3,8}/);
    expect(coreStyles).not.toMatch(/font-weight:\s*(7[5-9][0-9]|8[0-9]{2}|900)/);
    expect(coreStyles).not.toMatch(/border-radius:\s*999px/);
    expect(coreStyles).not.toMatch(/transform:\s*translateY/);
    expect(coreStyles).not.toMatch(
      /box-shadow:\s+(?!none;|var\(--shadow-(?:reading|hover|floating)\);)[^;]+;/,
    );
  });

  it("keeps rendered Org styled by semantic elements, not page-specific cards", () => {
    const renderedOrg = readFileSync("src/styles/rendered-org.css", "utf8");

    expect(renderedOrg).toContain(".rendered-html h2::before");
    expect(renderedOrg).toContain(".org-heading-todo--focus");
    expect(renderedOrg).toContain(".org-priority--a");
    expect(renderedOrg).toContain(".org-timestamp--active");
    expect(renderedOrg).toContain(".org-table-frame");
    expect(renderedOrg).toContain(".org-block-name");
    expect(renderedOrg).toContain(".org-meta-chip--deadline");
    expect(renderedOrg).toContain(".org-meta-row--properties div");
    expect(renderedOrg).toContain(".rendered-html pre");
    expect(renderedOrg).toContain("border-left: 3px solid var(--face-salient);");
    expect(renderedOrg).toContain(".rendered-html table");
    expect(renderedOrg).toContain(".rendered-html .todo");
    expect(renderedOrg).toContain(".rendered-html .done");
    expect(renderedOrg).toContain(".rendered-html .tag");
  });
});
